In [2]:
import torch

# 1차원 텐서 생성 (벡터)
tensor_1d = torch.tensor([1, 2, 3, 4, 5])

# 2차원 텐서 생성 (행렬)
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 0으로 채워진 3x3 텐서
zeros_tensor = torch.zeros(3, 3)

# 평균 0, 표준편차 1의 정규분포를 따르는 3x3 텐서
randn_tensor = torch.randn(3, 3)

print(tensor_1d)
print(tensor_2d)
print(zeros_tensor)
print(randn_tensor)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[-1.0695,  0.6484, -1.2045],
        [-0.3317,  1.3867,  1.2335],
        [-0.6120,  0.6494,  0.1371]])


In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 텐서 간 덧셈
result = a + b
# 또는 torch.add(a, b) 사용 가능
print(result)  # tensor([5, 7, 9])


tensor([5, 7, 9])


In [4]:
result = a - b
# 또는 torch.sub(a, b) 사용 가능
print(result)  # tensor([-3, -3, -3])


tensor([-3, -3, -3])


In [5]:
result = a * b
# 또는 torch.mul(a, b) 사용 가능
print(result)  # tensor([ 4, 10, 18])


tensor([ 4, 10, 18])


In [6]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

result = torch.matmul(a, b)
# 또는 a @ b
print(result)
# tensor([[19, 22],
#         [43, 50]])


tensor([[19, 22],
        [43, 50]])


In [7]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([2, 4, 5])

result = a / b
# 또는 torch.div(a, b) 사용 가능
print(result)  # tensor([5., 5., 6.])


tensor([5., 5., 6.])


In [8]:
a = torch.tensor([2, 3, 4])

# 텐서 요소 각각의 제곱
result = a ** 2
# 또는 torch.pow(a, 2)
print(result)  # tensor([ 4,  9, 16])


tensor([ 4,  9, 16])


In [9]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor.shape)  # torch.Size([2, 3])


torch.Size([2, 3])


In [10]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tensor.view(3, 2)  # 2x3 텐서를 3x2로 변경
print(reshaped_tensor)
# tensor([[1, 2],
#         [3, 4],
#         [5, 6]])


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [11]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 전체 합계
sum_value = torch.sum(tensor)
print(sum_value)  # tensor(21)

# 특정 차원의 합계
sum_value_dim0 = torch.sum(tensor, dim=0)  # 행을 기준으로 열의 합
print(sum_value_dim0)  # tensor([5, 7, 9])


tensor(21)
tensor([5, 7, 9])


In [12]:
tensor = torch.tensor([1, 2, 3, 4, 5])

# 최댓값
max_value = torch.max(tensor)
print(max_value)  # tensor(5)

# 최솟값
min_value = torch.min(tensor)
print(min_value)  # tensor(1)


tensor(5)
tensor(1)


In [13]:
tensor = torch.tensor([1, 2, 3, 4, 5])

# 3보다 큰 값들만 True
result = tensor > 3
print(result)  # tensor([False, False, False,  True,  True])


tensor([False, False, False,  True,  True])


In [14]:
import torch

# 예시 텐서 생성 (2x3 텐서)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 첫 번째 행만 선택
slice_1 = tensor[0, :]
print(slice_1)  # tensor([1, 2, 3])

# 두 번째 열만 선택
slice_2 = tensor[:, 1]
print(slice_2)  # tensor([2, 5])

# 두 번째 행과 세 번째 열의 원소 선택
slice_3 = tensor[1, 2]
print(slice_3)  # tensor(6)

# 특정 영역 (첫 번째 행의 첫 번째와 두 번째 열 선택)
slice_4 = tensor[0, 0:2]
print(slice_4)  # tensor([1, 2])


tensor([1, 2, 3])
tensor([2, 5])
tensor(6)
tensor([1, 2])


In [15]:
# 2x2 텐서 두 개 생성
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# 행 기준(0번 축)으로 붙이기 (2x2 + 2x2 = 4x2)
concat_1 = torch.cat((tensor_a, tensor_b), dim=0)
print(concat_1)
# tensor([[1, 2],
#         [3, 4],
#         [5, 6],
#         [7, 8]])

# 열 기준(1번 축)으로 붙이기 (2x2 + 2x2 = 2x4)
concat_2 = torch.cat((tensor_a, tensor_b), dim=1)
print(concat_2)
# tensor([[1, 2, 5, 6],
#         [3, 4, 7, 8]])


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [16]:
# 1차원 텐서를 2차원으로 변경
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
reshaped_tensor = tensor.view(2, 3)  # 2x3 텐서로 변환
print(reshaped_tensor)
# tensor([[1, 2, 3],
#         [4, 5, 6]])

# 다시 1차원으로 변경
flattened_tensor = reshaped_tensor.view(-1)  # -1은 나머지 요소를 자동으로 계산
print(flattened_tensor)  # tensor([1, 2, 3, 4, 5, 6])


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])


In [17]:
# 1x6 텐서를 3개의 텐서로 나누기
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
chunks = torch.chunk(tensor, 3)  # 3개의 텐서로 나눔
for chunk in chunks:
    print(chunk)
# tensor([1, 2])
# tensor([3, 4])
# tensor([5, 6])


tensor([1, 2])
tensor([3, 4])
tensor([5, 6])


In [18]:
# 1x6 텐서를 2개의 원소를 가지는 텐서로 나누기
splits = torch.split(tensor, 2)  # 각 텐서가 2개의 원소를 가짐
for split in splits:
    print(split)
# tensor([1, 2])
# tensor([3, 4])
# tensor([5, 6])


tensor([1, 2])
tensor([3, 4])
tensor([5, 6])


In [19]:
# 예시 텐서 생성 (4x4 텐서)
tensor = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# 2x2 텐서로 자르기
top_left = tensor[:2, :2]   # 왼쪽 상단
bottom_right = tensor[2:, 2:]  # 오른쪽 하단

# 자른 텐서 출력
print(top_left)
# tensor([[1, 2],
#         [5, 6]])

print(bottom_right)
# tensor([[11, 12],
#         [15, 16]])

# 자른 텐서를 다시 붙이기
new_tensor = torch.cat((top_left, bottom_right), dim=1)
print(new_tensor)
# tensor([[ 1,  2, 11, 12],
#         [ 5,  6, 15, 16]])


tensor([[1, 2],
        [5, 6]])
tensor([[11, 12],
        [15, 16]])
tensor([[ 1,  2, 11, 12],
        [ 5,  6, 15, 16]])


In [22]:
tensor = torch.tensor([[1, 2], [3, 4]])
# 데이터를 입력으로 받아서 텐서를 생성
print(tensor)

tensor([[1, 2],
        [3, 4]])


In [23]:
zeros_tensor = torch.zeros(3, 3)
# 모든 요소가 0인 텐서를 생성
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [24]:
ones_tensor = torch.ones(2, 4)
# 모든 요소가 1인 텐서를 생성
print(ones_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [27]:
rand_tensor = torch.rand(3, 3)
# 0과 1 사이의 균등 분포를 따르는 난수로 이루어진 텐서를 생성

In [26]:
randn_tensor = torch.randn(3, 3)
# 평균이 0이고 표준 편차가 1인 정규 분포를 따르는 난수로 이루어진 텐서를 생성

In [28]:
linspace_tensor = torch.linspace(0, 1, 5)  # tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
# 주어진 범위 내에서 일정 간격으로 나뉜 값을 가지는 1차원 텐서를 생성

In [ ]:
eye_tensor = torch.eye(3)  # 3x3 단위 행렬 생성
# 단위 행렬을 생성

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tensor.reshape(3, 2)  # tensor([[1, 2], [3, 4], [5, 6]])
# 텐서의 모양을 변경

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
transposed_tensor = tensor.transpose(0, 1)  # tensor([[1, 4], [2, 5], [3, 6]])
# 주어진 두 차원을 교환

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
flattened_tensor = tensor.flatten()  # tensor([1, 2, 3, 4, 5, 6])
# 여러 차원의 텐서를 1차원으로 평탄화

In [31]:
tensor = torch.tensor([[[1, 2, 3]]])  # shape: (1, 1, 3)
squeezed_tensor = torch.squeeze(tensor)  # tensor([1, 2, 3]) - shape: (3,)
# 차원이 1인 차원을 제거

In [30]:
tensor = torch.tensor([1, 2, 3])  # shape: (3,)
unsqueezed_tensor = torch.unsqueeze(tensor, 0)  # tensor([[1, 2, 3]]) - shape: (1, 3)
# 지정한 차원에 크기가 1인 차원을 추가


In [33]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])
concatenated_tensor = torch.cat((tensor_a, tensor_b), dim=0)  
# tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
# 주어진 차원을 기준으로 여러 텐서를 이어 붙이기
print(concatenated_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [34]:
tensor_a = torch.tensor([1, 2])
tensor_b = torch.tensor([3, 4])
stacked_tensor = torch.stack((tensor_a, tensor_b), dim=0)  # tensor([[1, 2], [3, 4]])
# 주어진 차원을 따라 여러 텐서를 쌓아 올리기

In [ ]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
split_tensors = torch.split(tensor, 2)  # 각 텐서의 크기가 2인 부분으로 나눔
for t in split_tensors:
    print(t)
# tensor([1, 2])
# tensor([3, 4])
# tensor([5, 6])
# 텐서를 일정한 크기로 나누기

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor.size())  # torch.Size([2, 3])
# 텐서의 크기 반환

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor.numel())  # 6
# 텐서의 총 원소 개수를 반환

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor.dim())  # 2
# 텐서의 차원 수를 반환

In [35]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
sum_all = torch.sum(tensor)  # 21
sum_dim0 = torch.sum(tensor, dim=0)  # tensor([5, 7, 9])
sum_dim1 = torch.sum(tensor, dim=1)  # tensor([6, 15])
# 지정한 차원의 합을 계산

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
mean_all = torch.mean(tensor.float())  # 3.5
mean_dim0 = torch.mean(tensor.float(), dim=0)  # tensor([2.5, 3.5, 4.5])
# 지정한 차원의 평균을 계산

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
max_value = torch.max(tensor)  # 6
# 지정한 차원에서 최솟값을 반환

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
max_index = torch.argmax(tensor)  # 5 (1차원 인덱스)
max_index_dim1 = torch.argmax(tensor, dim=1)  # tensor([2, 2]) (각 행에서 최대값의 인덱스)
# 지정된 차원에서 최대값의 인덱스를 반환

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
min_index = torch.argmin(tensor)  # 0 (1차원 인덱스)
min_index_dim1 = torch.argmin(tensor, dim=1)  # tensor([0, 0]) (각 행에서 최솟값의 인덱스)
# 지정된 차원에서 최솟값의 인덱스를 반환

In [ ]:
tensor = torch.tensor([3, 1, 2, 5, 4])
sorted_tensor, sorted_indices = torch.sort(tensor)
print(sorted_tensor)  # tensor([1, 2, 3, 4, 5])
print(sorted_indices)  # tensor([1, 2, 0, 4, 3])
# 텐서를 정렬

In [ ]:
tensor = torch.tensor([1, 3, 2, 5, 4])
top_values, top_indices = torch.topk(tensor, k=3)
print(top_values)  # tensor([5, 4, 3])
print(top_indices)  # tensor([3, 4, 1])
# 가장 큰 값 k개를 반환

In [ ]:
tensor = torch.tensor([0.5, 2.0, 3.5, 5.0, 7.0])
clamped_tensor = torch.clamp(tensor, min=1.0, max=5.0)
print(clamped_tensor)  # tensor([1.0, 2.0, 3.5, 5.0, 5.0])
# 텐서의 값을 지정한 범위로 제한

In [ ]:
tensor = torch.tensor([1, 2, 3, 4, 5])
condition = tensor > 3
result = torch.where(condition, tensor, torch.tensor(0))
print(result)  # tensor([0, 0, 0, 4, 5])
# 조건에 따라 요소를 선택

In [ ]:
tensor = torch.tensor([[0, 1, 0], [2, 0, 3]])
non_zero_indices = torch.nonzero(tensor)
print(non_zero_indices)
# tensor([[0, 1],
#         [1, 0],
#         [1, 2]])
# 0이 아닌 요소의 인덱스를 반환

In [ ]:
tensor = torch.tensor([0, 1, 2, 3])
print(torch.any(tensor))  # True (0이 아닌 요소가 있음)
print(torch.all(tensor))  # False (0이 있음)
# torch.any(): 텐서의 요소 중 하나라도 참이면 True를 반환
# torch.all(): 텐서의 모든 요소가 참이면 True를 반환

In [ ]:
tensor = torch.tensor([1, 2, 3, 4])
cumsum_tensor = torch.cumsum(tensor, dim=0)
print(cumsum_tensor)  # tensor([ 1,  3,  6, 10])

cumprod_tensor = torch.cumprod(tensor, dim=0)
print(cumprod_tensor)  # tensor([ 1,  2,  6, 24])

# torch.cumsum(): 누적 합을 계산
# torch.cumprod(): 누적 곱을 계산

In [36]:
import numpy as np

# 행렬 A 정의 (2x3 행렬)
A = np.array([[1, 2, 3],
            [4, 5, 6]])

# 행렬 B 정의 (3x2 행렬)
B = np.array([[7, 8],
            [9, 10],
            [11, 12]])

# 행렬 곱셈 수행 (A @ B 또는 np.dot(A, B) 사용 가능)
C = np.matmul(A, B)
# 또는 C = np.dot(A, B)
# 또는 C = A @ B

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n행렬 A와 B의 곱 C:")
print(C)

# NumPy를 이용한 행렬 곱셈 

행렬 A:
[[1 2 3]
 [4 5 6]]

행렬 B:
[[ 7  8]
 [ 9 10]
 [11 12]]

행렬 A와 B의 곱 C:
[[ 58  64]
 [139 154]]


In [37]:
import torch

# 행렬 A 정의 (2x3 텐서)
A = torch.tensor([[1, 2, 3],
                [4, 5, 6]])

# 행렬 B 정의 (3x2 텐서)
B = torch.tensor([[7, 8],
                [9, 10],
                [11, 12]])

# 행렬 곱셈 수행
C = torch.matmul(A, B)
# 또는 C = A @ B

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n행렬 A와 B의 곱 C:")
print(C)

# PyTorch를 이용한 행렬 곱셈

행렬 A:
tensor([[1, 2, 3],
        [4, 5, 6]])

행렬 B:
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

행렬 A와 B의 곱 C:
tensor([[ 58,  64],
        [139, 154]])


In [38]:
# 요소별 곱셈 (Element-wise Multiplication)
# 요소별 곱셈은 동일한 위치의 요소들끼리 곱하는 연산으로, Hadamard 곱

import numpy as np

# 동일한 크기의 행렬 정의
A = np.array([[1, 2],
            [3, 4]])

B = np.array([[5, 6],
            [7, 8]])

# 요소별 곱셈
C_elementwise = A * B

print("요소별 곱셈 결과:")
print(C_elementwise)

요소별 곱셈 결과:
[[ 5 12]
 [21 32]]


In [39]:
# 행렬 곱셈 (Matrix Multiplication)
# 위의 행렬 A와 B에 대해 행렬 곱셈을 수행하면:
# 행렬 곱셈
C_matrix = np.matmul(A, B)
# 또는 C_matrix = A @ B

print("\n행렬 곱셈 결과:")
print(C_matrix)




행렬 곱셈 결과:
[[19 22]
 [43 50]]


차이점!
# 요소별 곱셈은 각 위치의 요소를 단순히 곱하는 것이며, 결과 행렬의 크기는 원본 행렬과 동일합니다.
# 행렬 곱셈은 선형 대수의 규칙에 따라 계산되며, 결과 행렬의 크기는 (A의 행 수 x B의 열 수)입니다.

In [40]:
import numpy as np

# 행렬 A 정의
A = np.array([[1, 2],
            [3, 4]])

# 행렬 B 정의
B = np.array([[5, 6],
            [7, 8]])

# 요소별 곱셈
C_elementwise = A * B

# 행렬 곱셈
C_matrix = np.matmul(A, B)
# 또는 C_matrix = A @ B

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n요소별 곱셈 결과:")
print(C_elementwise)
print("\n행렬 곱셈 결과:")
print(C_matrix)


행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]

요소별 곱셈 결과:
[[ 5 12]
 [21 32]]

행렬 곱셈 결과:
[[19 22]
 [43 50]]


요약 및 정리
행렬 곱셈은 선형 변환을 적용하는 연산으로, 머신러닝 모델에서 입력 데이터에 가중치를 적용할 때 사용됩니다.
요소별 곱셈은 동일한 위치의 요소를 곱하는 연산으로, 신경망에서 주로 활성화 맵을 조정하거나 마스크를 적용할 때 사용됩니다.
Python의 NumPy와 PyTorch는 모두 행렬 연산을 효율적으로 수행할 수 있는 함수와 메소드를 제공합니다.